services:
  pansou-api:
    image: ghcr.io/fish2018/pansou:latest
    container_name: pansou-api
    ports:
      - 8888:8888
    volumes:
      - /vol1/1000/Docker/pansou-api/cache:/app/cache
    environment:
      - PORT=8888
      - AUTH_ENABLED=true
      - AUTH_USERS=admin:password
      - AUTH_TOKEN_EXPIRY=24
      - AUTH_JWT_SECRET=72d2f01e7819c365894b2136ac70d24807f297097e857034d82577d91234abcd
    restart: always
    network_mode: bridge
